// GSDML (General Station Description Markup Language) of PROFINET IO-Devices:
// - generation of the file describing a VirtualPLC CPU used as IO-Device, to import into
//   the engineering tool of the IO-Controller;
// - reading of third-party device files, to configure them under a VirtualPLC CPU used
//   as IO-Controller (access point, modules, data lengths, default parameter records).
import type { PnSubmodule } from './image.ts';
import { childXml, childrenXml, findXml, parseXml, walkXml, type XmlNode } from './xml.ts';

// ---------------------------------------------------------------------------
// Generation (VirtualPLC as IO-Device) — module catalogue shared with the CPU
// (runtime/platform/linux/profinet/pn_device.h)
// ---------------------------------------------------------------------------

export const PN_DAP_MODULE = 0x00000001;
export const PN_DAP_SUBMODULE = 0x00000001;
export const PN_INTERFACE_SUBMODULE = 0x00000002;
export const PN_PORT_SUBMODULE = 0x00000003;
export const PN_MODULE_SIZES = [1, 2, 4, 8, 16, 32, 64, 128];
/** Ident of an IO module of the VirtualPLC catalogue: 0x0000KKNN (KK 1 in, 2 out, 3 in/out; NN bytes) */
export const pnModuleIdent = (kind: 'in' | 'out' | 'inout', size: number) => (({ in: 1, out: 2, inout: 3 })[kind] << 8) | size;

export interface GsdmlOptions {
  vendorId: number;
  deviceId: number;
  vendorName?: string;
  deviceName?: string;
  /** For the file name (yyyymmdd); default today */
  date?: Date;
}

const hex = (v: number, digits: number) => `0x${v.toString(16).toUpperCase().padStart(digits, '0')}`;
const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function generateGsdml(o: GsdmlOptions): { fileName: string; xml: string } {
  const vendor = o.vendorName ?? 'VirtualPLC';
  const device = o.deviceName ?? 'VirtualPLC CPU';
  const d = o.date ?? new Date();
  const stamp = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;
  const texts: Array<[string, string, string]> = [
    ['IDT_INFO_Device', `${device} used as PROFINET IO-Device`, `${device} utilisée comme IO-Device PROFINET`],
    ['IDT_NAME_DAP', device, device],
    ['IDT_INFO_DAP', 'Exchanges process data with the IO-Controller: its outputs go to %I, its inputs come from %Q (slot order)',
      "Échange des données avec l'IO-Controller : ses sorties vont dans %I, ses entrées viennent de %Q (ordre des emplacements)"],
    ['IDT_NAME_IF', 'Interface', 'Interface'],
    ['IDT_NAME_PORT1', 'Port 1', 'Port 1'],
    ['IDT_DATA_IN', 'Input data', "Données d'entrée"],
    ['IDT_DATA_OUT', 'Output data', 'Données de sortie'],
  ];
  const modules: string[] = [];
  const refs: string[] = [];
  for (const kind of ['in', 'out', 'inout'] as const) {
    for (const size of PN_MODULE_SIZES) {
      const id = `${kind.toUpperCase()}_${size}`;
      const ident = hex(pnModuleIdent(kind, size), 8);
      const label = { in: ['IN', 'Input'], out: ['OUT', 'Output'], inout: ['IN/OUT', 'Input/output'] }[kind];
      const fr = { in: 'Entrée', out: 'Sortie', inout: 'Entrée/sortie' }[kind];
      texts.push([`IDT_NAME_${id}`, `${label[0]} ${size} byte${size > 1 ? 's' : ''}`, `${label[0]} ${size} octet${size > 1 ? 's' : ''}`]);
      texts.push([`IDT_INFO_${id}`, `${label[1]} data, ${size} byte${size > 1 ? 's' : ''}`, `${fr}, ${size} octet${size > 1 ? 's' : ''}`]);
      refs.push(`          <ModuleItemRef ModuleItemTarget="${id}" AllowedInSlots="1..64"/>`);
      const input = kind !== 'out' ? `<Input><DataItem DataType="OctetString" Length="${size}" TextId="IDT_DATA_IN"/></Input>` : '';
      const output = kind !== 'in' ? `<Output><DataItem DataType="OctetString" Length="${size}" TextId="IDT_DATA_OUT"/></Output>` : '';
      modules.push(`        <ModuleItem ID="${id}" ModuleIdentNumber="${ident}">
          <ModuleInfo><Name TextId="IDT_NAME_${id}"/><InfoText TextId="IDT_INFO_${id}"/><OrderNumber Value="VPLC-${label[0].replace('/', '')}${size}"/></ModuleInfo>
          <VirtualSubmoduleList>
            <VirtualSubmoduleItem ID="${id}_SUB" SubmoduleIdentNumber="${ident}" MayIssueProcessAlarm="false">
              <IOData>${input}${output}</IOData>
              <ModuleInfo><Name TextId="IDT_NAME_${id}"/><InfoText TextId="IDT_INFO_${id}"/></ModuleInfo>
            </VirtualSubmoduleItem>
          </VirtualSubmoduleList>
        </ModuleItem>`);
    }
  }
  const xml = `<?xml version="1.0" encoding="utf-8"?>
<!-- GSDML of a ${esc(vendor)} CPU used as PROFINET IO-Device (generated by VirtualPLC Studio) -->
<ISO15745Profile xmlns="http://www.profibus.com/GSDML/2003/11/DeviceProfile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.profibus.com/GSDML/2003/11/DeviceProfile ..\\xsd\\GSDML-DeviceProfile-V2.35.xsd">
  <ProfileHeader>
    <ProfileIdentification>PROFINET Device Profile</ProfileIdentification>
    <ProfileRevision>1.00</ProfileRevision>
    <ProfileName>Device Profile for PROFINET Devices</ProfileName>
    <ProfileSource>PROFIBUS Nutzerorganisation e. V. (PNO)</ProfileSource>
    <ProfileClassID>Device</ProfileClassID>
    <ISO15745Reference>
      <ISO15745Part>4</ISO15745Part>
      <ISO15745Edition>1</ISO15745Edition>
      <ProfileTechnology>GSDML</ProfileTechnology>
    </ISO15745Reference>
  </ProfileHeader>
  <ProfileBody>
    <DeviceIdentity VendorID="${hex(o.vendorId, 4)}" DeviceID="${hex(o.deviceId, 4)}">
      <InfoText TextId="IDT_INFO_Device"/>
      <VendorName Value="${esc(vendor)}"/>
    </DeviceIdentity>
    <DeviceFunction>
      <Family MainFamily="PLCs" ProductFamily="${esc(vendor)}"/>
    </DeviceFunction>
    <ApplicationProcess>
      <DeviceAccessPointList>
        <DeviceAccessPointItem ID="DAP_1" PhysicalSlots="0..64" ModuleIdentNumber="${hex(PN_DAP_MODULE, 8)}" MinDeviceInterval="128" ImplementationType="VirtualPLC" DNS_CompatibleName="virtualplc" FixedInSlots="0" ObjectUUID_LocalIndex="1" DeviceAccessSupported="false" MultipleWriteSupported="true" CheckDeviceID_Allowed="true" NameOfStationNotTransferable="false" LLDP_NoD_Supported="false" ResetToFactoryModes="2">
          <ModuleInfo>
            <Name TextId="IDT_NAME_DAP"/>
            <InfoText TextId="IDT_INFO_DAP"/>
            <VendorName Value="${esc(vendor)}"/>
            <OrderNumber Value="VPLC-CPU"/>
            <HardwareRelease Value="1"/>
            <SoftwareRelease Value="V1.0.0"/>
          </ModuleInfo>
          <CertificationInfo ConformanceClass="A" ApplicationClass="" NetloadClass="I"/>
          <IOConfigData MaxInputLength="1440" MaxOutputLength="1440"/>
          <UseableModules>
${refs.join('\n')}
          </UseableModules>
          <VirtualSubmoduleList>
            <VirtualSubmoduleItem ID="DAP_1_SUB" SubmoduleIdentNumber="${hex(PN_DAP_SUBMODULE, 8)}" MayIssueProcessAlarm="false">
              <IOData/>
              <ModuleInfo><Name TextId="IDT_NAME_DAP"/><InfoText TextId="IDT_INFO_DAP"/></ModuleInfo>
            </VirtualSubmoduleItem>
          </VirtualSubmoduleList>
          <SystemDefinedSubmoduleList>
            <InterfaceSubmoduleItem ID="DAP_1_IF" SubslotNumber="32768" SubmoduleIdentNumber="${hex(PN_INTERFACE_SUBMODULE, 8)}" SupportedRT_Classes="RT_CLASS_1" TextId="IDT_NAME_IF" SupportedProtocols="SNMP;LLDP" DCP_BoundarySupported="true" PTP_BoundarySupported="true">
              <ApplicationRelations StartupMode="Legacy">
                <TimingProperties SendClock="32" ReductionRatio="4 8 16 32 64 128 256 512"/>
              </ApplicationRelations>
            </InterfaceSubmoduleItem>
            <PortSubmoduleItem ID="DAP_1_PORT1" SubslotNumber="32769" SubmoduleIdentNumber="${hex(PN_PORT_SUBMODULE, 8)}" TextId="IDT_NAME_PORT1" MaxPortRxDelay="350" MaxPortTxDelay="160">
              <MAUTypeList><MAUTypeItem Value="16"/></MAUTypeList>
            </PortSubmoduleItem>
          </SystemDefinedSubmoduleList>
        </DeviceAccessPointItem>
      </DeviceAccessPointList>
      <ModuleList>
${modules.join('\n')}
      </ModuleList>
      <ExternalTextList>
        <PrimaryLanguage>
${texts.map(([id, en]) => `          <Text TextId="${id}" Value="${esc(en)}"/>`).join('\n')}
        </PrimaryLanguage>
        <Language xml:lang="fr">
${texts.map(([id, , fr]) => `          <Text TextId="${id}" Value="${esc(fr)}"/>`).join('\n')}
        </Language>
      </ExternalTextList>
    </ApplicationProcess>
  </ProfileBody>
</ISO15745Profile>
`;
  const token = (s: string) => s.replace(/[^A-Za-z0-9]+/g, '').slice(0, 20) || 'VPLC';
  return { fileName: `GSDML-V2.35-${token(vendor)}-${token(device)}-${stamp}.xml`, xml };
}

// ---------------------------------------------------------------------------
// Reading of third-party GSDML files
// ---------------------------------------------------------------------------

export interface GsdRecord {
  index: number;
  /** Default content of the parameter record */
  data: number[];
}

export interface GsdSubmodule {
  id: string;
  name: string;
  subslot: number;
  ident: number;
  inLength: number;
  outLength: number;
  records: GsdRecord[];
}

export interface GsdModule {
  id: string;
  name: string;
  info: string;
  orderNumber?: string;
  ident: number;
  submodules: GsdSubmodule[];
}

export interface GsdDap extends GsdModule {
  /** Slots of the device (e.g. 0..64) */
  physicalSlots: number[];
  /** Modules that can be plugged, with their slots */
  useable: Array<{ moduleId: string; allowedSlots: number[]; fixedInSlots: number[]; usedInSlots: number[] }>;
  minDeviceIntervalMs: number;
}

export interface GsdDevice {
  vendorId: number;
  deviceId: number;
  vendorName: string;
  info: string;
  family?: string;
  daps: GsdDap[];
  modules: Map<string, GsdModule>;
}

/** "1..4 6 8..10" → [1,2,3,4,6,8,9,10] */
function slotList(s: string | undefined): number[] {
  const out: number[] = [];
  for (const part of (s ?? '').trim().split(/\s+/).filter(Boolean)) {
    const m = /^(\d+)\.\.(\d+)$/.exec(part);
    if (m) for (let i = Number(m[1]); i <= Number(m[2]) && out.length < 10000; i++) out.push(i);
    else if (/^\d+$/.test(part)) out.push(Number(part));
  }
  return out;
}

const SIZES: Record<string, number> = {
  Integer8: 1, Unsigned8: 1, Integer16: 2, Unsigned16: 2, Integer32: 4, Unsigned32: 4, Integer64: 8, Unsigned64: 8,
  Float32: 4, Float64: 8, Date: 7, TimeOfDay: 6, TimeDifference: 6, N2: 2, N4: 4, V2: 2, E2: 2, C4: 4, X2: 2, X4: 4,
  Unipolar2_16: 2, Boolean: 1, 'Float32+Status8': 5, 'Integer8+Status8': 2, 'Integer16+Status8': 3, 'Integer32+Status8': 5,
  'Unsigned8+Unsigned8': 2, 'Unsigned16_S': 2, 'Integer16_S': 2, 'Unsigned8_S': 1, 'Integer8_S': 1, OctetString_S: 1, F_MessageTrailer4Byte: 4, F_MessageTrailer5Byte: 5,
};

function dataLength(io: XmlNode | undefined): number {
  let n = 0;
  for (const it of childrenXml(io, 'DataItem')) {
    const t = it.attrs.DataType ?? '';
    n += it.attrs.Length ? Number(it.attrs.Length) : SIZES[t] ?? 0;
  }
  return n;
}

/** Default content of a ParameterRecordDataItem: Const blocks, then Ref default values. */
function recordOf(item: XmlNode, valueItems: Map<string, XmlNode>): GsdRecord {
  const length = Number(item.attrs.Length ?? 0);
  const data = new Array<number>(length).fill(0);
  for (const c of childrenXml(item, 'Const')) {
    const off = Number(c.attrs.ByteOffset ?? 0);
    (c.attrs.Data ?? '').split(',').map((x) => x.trim()).filter(Boolean).forEach((x, i) => {
      if (off + i < length) data[off + i] = Number(x) & 0xFF;
    });
  }
  for (const r of childrenXml(item, 'Ref')) {
    const off = Number(r.attrs.ByteOffset ?? 0);
    const bit = r.attrs.BitOffset !== undefined ? Number(r.attrs.BitOffset) : undefined;
    const type = r.attrs.DataType ?? 'Unsigned8';
    let value = Number(r.attrs.DefaultValue ?? 0);
    if (!Number.isFinite(value) && r.attrs.ValueItemTarget) value = 0;
    void valueItems;
    if (type === 'Bit' || type === 'BitArea') {
      const width = type === 'Bit' ? 1 : Number(r.attrs.BitLength ?? 1);
      const b = bit ?? 0;
      for (let i = 0; i < width; i++) {
        const byte = off + Math.floor((b + i) / 8);
        if (byte >= length) continue;
        const mask = 1 << ((b + i) % 8);
        data[byte] = (value >> i) & 1 ? data[byte] | mask : data[byte] & ~mask;
      }
      continue;
    }
    const size = SIZES[type] ?? 1;
    const v = BigInt.asUintN(size * 8, BigInt(Math.trunc(value)));
    for (let i = 0; i < size; i++) if (off + i < length) data[off + i] = Number((v >> BigInt(8 * (size - 1 - i))) & 0xFFn);  // big endian
  }
  return { index: Number(item.attrs.Index), data };
}

export function parseGsdml(xml: string, language = 'fr'): GsdDevice {
  const doc = parseXml(xml);
  const identity = findXml(doc, 'DeviceIdentity');
  if (!identity || !findXml(doc, 'DeviceAccessPointList')) throw new Error('Not a GSDML file (DeviceIdentity / DeviceAccessPointList expected)');
  const texts = new Map<string, string>();
  const list = findXml(doc, 'ExternalTextList');
  for (const t of childrenXml(childXml(list, 'PrimaryLanguage'), 'Text')) texts.set(t.attrs.TextId, t.attrs.Value ?? t.text);
  const lang = childrenXml(list, 'Language').find((l) => (l.attrs['xml:lang'] ?? l.attrs.lang ?? '').startsWith(language));
  for (const t of childrenXml(lang, 'Text')) texts.set(t.attrs.TextId, t.attrs.Value ?? t.text);
  const text = (n: XmlNode | undefined) => (n?.attrs.TextId ? texts.get(n.attrs.TextId) ?? n.attrs.TextId : n?.attrs.Value ?? '');
  const valueItems = new Map<string, XmlNode>();
  for (const v of walkXml(doc)) if (v.name === 'ValueItem' && v.attrs.ID) valueItems.set(v.attrs.ID, v);

  const submodule = (s: XmlNode, defaultSubslot: number): GsdSubmodule => {
    const io = childXml(s, 'IOData');
    const info = childXml(s, 'ModuleInfo');
    const records = childrenXml(childXml(s, 'RecordDataList'), 'ParameterRecordDataItem').map((r) => recordOf(r, valueItems));
    return {
      id: s.attrs.ID ?? '',
      name: text(childXml(info, 'Name')) || text(s),
      subslot: Number(s.attrs.SubslotNumber ?? defaultSubslot),
      ident: Number(s.attrs.SubmoduleIdentNumber ?? 0),
      inLength: dataLength(childXml(io, 'Input')),
      outLength: dataLength(childXml(io, 'Output')),
      records,
    };
  };
  const moduleOf = (m: XmlNode): GsdModule => {
    const info = childXml(m, 'ModuleInfo');
    const subs = childrenXml(childXml(m, 'VirtualSubmoduleList'), 'VirtualSubmoduleItem').map((s) => submodule(s, 1));
    const system = childXml(m, 'SystemDefinedSubmoduleList');
    for (const s of childrenXml(system, 'InterfaceSubmoduleItem')) subs.push(submodule(s, 0x8000));
    childrenXml(system, 'PortSubmoduleItem').forEach((s, i) => subs.push(submodule(s, 0x8001 + i)));
    return {
      id: m.attrs.ID ?? '',
      name: text(childXml(info, 'Name')),
      info: text(childXml(info, 'InfoText')),
      orderNumber: childXml(info, 'OrderNumber')?.attrs.Value,
      ident: Number(m.attrs.ModuleIdentNumber ?? 0),
      submodules: subs,
    };
  };
  const modules = new Map<string, GsdModule>();
  for (const m of childrenXml(findXml(doc, 'ModuleList'), 'ModuleItem')) modules.set(m.attrs.ID, moduleOf(m));
  const daps: GsdDap[] = childrenXml(findXml(doc, 'DeviceAccessPointList'), 'DeviceAccessPointItem').map((d) => ({
    ...moduleOf(d),
    physicalSlots: slotList(d.attrs.PhysicalSlots),
    minDeviceIntervalMs: Number(d.attrs.MinDeviceInterval ?? 32) / 32,
    useable: childrenXml(childXml(d, 'UseableModules'), 'ModuleItemRef').map((r) => ({
      moduleId: r.attrs.ModuleItemTarget,
      allowedSlots: slotList(r.attrs.AllowedInSlots ?? r.attrs.FixedInSlots ?? r.attrs.UsedInSlots),
      fixedInSlots: slotList(r.attrs.FixedInSlots),
      usedInSlots: slotList(r.attrs.UsedInSlots),
    })),
  }));
  const family = findXml(doc, 'Family');
  return {
    vendorId: Number(identity.attrs.VendorID ?? 0),
    deviceId: Number(identity.attrs.DeviceID ?? 0),
    vendorName: childXml(identity, 'VendorName')?.attrs.Value ?? '',
    info: text(childXml(identity, 'InfoText')),
    family: family ? `${family.attrs.MainFamily ?? ''}${family.attrs.ProductFamily ? ` / ${family.attrs.ProductFamily}` : ''}` : undefined,
    daps,
    modules,
  };
}

/**
 * Submodules of a configured device: the access point in slot 0, then the plugged
 * modules (fixed ones included), with process image addresses from inByte / outByte.
 */
export function pnSubmodules(dap: GsdDap, plugged: Array<{ slot: number; module: GsdModule }>, inByte: number, outByte: number): Array<PnSubmodule & { records: GsdRecord[]; name: string }> {
  const out: Array<PnSubmodule & { records: GsdRecord[]; name: string }> = [];
  let i = inByte;
  let q = outByte;
  const add = (slot: number, m: GsdModule) => {
    for (const s of m.submodules) {
      out.push({
        slot, subslot: s.subslot, moduleIdent: m.ident, submoduleIdent: s.ident, name: s.name || m.name,
        inLength: s.inLength, inByte: s.inLength ? i : 0, outLength: s.outLength, outByte: s.outLength ? q : 0, records: s.records,
      });
      i += s.inLength;
      q += s.outLength;
    }
  };
  add(0, dap);
  for (const p of [...plugged].sort((a, b) => a.slot - b.slot)) add(p.slot, p.module);
  return out;
}
