// PROFINET IO-Device (RT_CLASS_1): this CPU as a device of an external IO-Controller.
//
// - DCP: identify, get / set name of station and IP parameters, signal, reset to factory
// - Connection establishment over DCE/RPC (connect, write records, PrmEnd,
//   ApplicationReady, release, read I&M0)
// - Cyclic data exchange (one input and one output IOCR), watchdog
//
// Modules (see the GSDML generated by the Studio): slot 0 holds the access point
// (interface 0x8000, port 0x8001); IO modules have the ident 0x0000KKNN where KK is
// 01 (input), 02 (output) or 03 (input + output) and NN the size in bytes (1..250).
// Output data of the controller are written to %I from inByte, the input data it
// reads come from %Q from outByte, in slot order.
#pragma once
#include <stdint.h>

#include <atomic>
#include <deque>
#include <set>
#include <functional>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#include "pn_net.h"
#include "pn_proto.h"
#include "pn_stack.h"

namespace vplc {
namespace pn {

struct DeviceConfig {
    std::string ifname = "eth0";
    std::string stationName;  // initial name (a name set by DCP and saved has priority)
    std::string dataDir;      // where the name / IP set by DCP are kept
    uint16_t vendorId = 0, deviceId = 1;
    uint16_t inByte = 0, inLength = 0;    // %I area written by the controller
    uint16_t outByte = 0, outLength = 0;  // %Q area read by the controller
    bool manageIp = true;                 // apply the IP parameters set by DCP to the interface
    std::string vendorName = "VirtualPLC";
    std::string orderId = "VPLC-CPU";
    std::string serial = "0001";
    std::function<void(const std::string&)> log;
};

/** Module catalogue shared with the GSDML (see file comment). */
constexpr uint32_t DAP_MODULE_IDENT = 0x00000001;
constexpr uint32_t DAP_SUBMODULE_IDENT = 0x00000001;
constexpr uint32_t INTERFACE_SUBMODULE_IDENT = 0x00000002;
constexpr uint32_t PORT_SUBMODULE_IDENT = 0x00000003;
/** Expected data lengths of a module ident; false if unknown */
bool catalogModule(uint16_t slot, uint16_t subslot, uint32_t moduleIdent, uint32_t submoduleIdent, uint16_t& inLength, uint16_t& outLength);

class Device : public Role {
public:
    explicit Device(DeviceConfig config);
    ~Device() override;
    /** Serves the device on the stack of its interface (before the stack starts). */
    void attach(Stack& stack);
    bool running() const { return stack_ && stack_->running(); }
    const DeviceConfig& config() const { return config_; }

    /** Controller outputs → process image inputs (called before each scan) */
    void readInputs(uint8_t* image, uint32_t size);
    /** Process image outputs → controller inputs (called after each scan) */
    void writeOutputs(const uint8_t* image, uint32_t size, bool run);

    bool connected() const { return state_.load() == AR_RUN; }
    /**
     * Alarm to the controller (PN_ALARM of the program): kind 1 = diagnosis appears
     * (code = channel error type), 12 = diagnosis disappears, 2 = process alarm (code =
     * 32-bit value). False when not exchanging data, slot unknown or queue full.
     */
    bool alarm(uint16_t slot, uint16_t kind, uint32_t code);
    /** Active diagnoses sent by this device */
    bool diagnosisActive();
    std::string stationName();
    std::string status();

private:
    enum ArState { AR_NONE, AR_WAIT_PRMEND, AR_WAIT_APPREADY_RES, AR_RUN };
    struct Mapped {
        uint16_t slot, subslot;
        uint16_t inLength, outLength;  // input: device → controller
        int32_t imageIn = -1;          // %I offset of the output data (controller → device)
        int32_t imageOut = -1;         // %Q offset of the input data
        uint16_t inOffset = 0, inIops = 0, outOffset = 0, outIops = 0;
        bool hasIn = false, hasOut = false;
        uint32_t moduleIdent = 0, submoduleIdent = 0;
    };
    struct PendingAlarm {
        AlarmInfo info;
    };
    void alarmTick(uint64_t now);
    void sendAlarm();
    void sendRtaAck(uint16_t ackSeq, bool high);
    void announceDiagnoses();

    void onFrame(const uint8_t* p, size_t n) override;
    bool onRpc(const uint8_t* p, size_t n, const sockaddr_in& from) override;
    uint64_t tick(uint64_t now) override;
    void log(const std::string& text);
    RawSocket& raw() { return stack_->raw(); }
    UdpSocket& rpc() { return stack_->rpc(); }
    void onDcp(const EthFrame& eth, const DcpMessage& m);
    void onDcpGet(const EthFrame& eth, const DcpMessage& m, const uint8_t* data, size_t n);
    void onDcpSet(const EthFrame& eth, const DcpMessage& m);
    void addIdentityBlocks(DcpBuilder& b, bool all, const uint8_t* wanted, size_t n);
    void onCyclic(uint16_t frameId, const uint8_t* p, size_t n);
    void onAlarm(const EthFrame& eth, const uint8_t* p, size_t n);
    void rpcRequest(const RpcHeader& h, const uint8_t* body, size_t n, const sockaddr_in& from);
    uint32_t connect(const std::vector<Block>& blocks, const sockaddr_in& from, Writer& w);
    uint32_t control(const std::vector<Block>& blocks, Writer& w);
    uint32_t release(const std::vector<Block>& blocks, Writer& w);
    uint32_t write(const std::vector<Block>& blocks, const uint8_t* end, Writer& w);
    uint32_t read(const std::vector<Block>& blocks, Writer& w);
    void sendAppReady();
    void sendCyclic();
    void abort(const std::string& why);
    void loadSettings();
    void saveSettings();

    DeviceConfig config_;
    Stack* stack_ = nullptr;

    std::mutex nameMutex_;
    std::string name_;
    Ipv4 ip_;
    uint32_t serverBoot_ = 0;

    // AR (one at a time)
    std::atomic<int> state_{AR_NONE};
    ArInfo ar_;
    IocrInfo in_, out_;  // input CR (we send), output CR (we receive)
    uint16_t alarmRemoteRef_ = 0, alarmLocalRef_ = 1;
    // alarm transmission (one outstanding alarm, RTA window size 1)
    std::mutex alarmMutex_;
    std::deque<AlarmInfo> alarmQueue_;
    std::set<uint32_t> diagnoses_;  // (slot << 16 | error type) of the active diagnoses
    bool alarmBusy_ = false, alarmTransportAcked_ = false;
    AlarmInfo alarmCurrent_;
    uint16_t rtaSendSeq_ = 0xFFFF, rtaRecvSeq_ = 0xFFFE, alarmSeqNo_ = 0;
    uint64_t alarmSentAt_ = 0;
    int alarmTries_ = 0;
    uint16_t rtaTimeoutMs_ = 100, rtaRetries_ = 3;
    sockaddr_in controller_{};
    std::vector<Mapped> mapped_;
    uint64_t nextSend_ = 0, lastRx_ = 0, connectedAt_ = 0, appReadySent_ = 0;
    int appReadyTries_ = 0;
    uint16_t cycleCounter_ = 0;
    Uuid appReadyActivity_;
    uint32_t appReadySeq_ = 0;
    // RPC retransmission: last response per activity
    Uuid lastActivity_;
    uint32_t lastSequence_ = 0xFFFFFFFF;
    std::vector<uint8_t> lastResponse_;

    // process data exchanged with the scan
    std::mutex ioMutex_;
    std::vector<uint8_t> fromController_;  // image of the %I area
    std::vector<uint8_t> toController_;    // image of the %Q area
    bool plcRun_ = false;
    uint64_t lastWrite_ = 0;  // outputs older than 500 ms: the CPU is not running
    bool controllerRun_ = false;
    std::vector<uint8_t> frame_;
    std::vector<uint8_t> csdu_;  // C_SDU of the last input frame (resent when the image is busy)
    bool lastRun_ = false;
    uint32_t records_ = 0;  // parameter records received (diagnostics)
};

}  // namespace pn
}  // namespace vplc
